// Code generated by logcopter-gen; DO NOT EDIT.

package production

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.internal.sections.production")
