// Code generated by logcopter-gen; DO NOT EDIT.

package oidcbroker

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.internal.pluginhost.oidcbroker")
