apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tinyidp-jitsi-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: tinyidp-jitsi
  mount: kv
  type: kv-v2
  path: apps/tinyidp-jitsi/prod/runtime
  refreshAfter: 30s
  destination:
    name: tinyidp-jitsi-runtime
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: tinyidp
    - kind: StatefulSet
      name: jitsi-jitsi-meet-prosody
    - kind: Deployment
      name: jitsi-jitsi-meet-jicofo
    - kind: Deployment
      name: jitsi-jitsi-meet-jvb-0
