apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinyidp-jitsi
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
imagePullSecrets:
  - name: tinyidp-jitsi-ghcr-pull
