// Code generated by logcopter-gen; DO NOT EDIT.

package idpemailchallenge

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.pkg.idpemailchallenge")
