// Code generated by logcopter-gen; DO NOT EDIT.

package xgojaruntime

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.cmd.tinyidp-xapp.internal.xgojaruntime")
