// Code generated by logcopter-gen; DO NOT EDIT.

package passwordhash

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.internal.passwordhash")
