// Code generated by logcopter-gen; DO NOT EDIT.

package smtpmailer

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.pkg.idpemailchallenge.smtpmailer")
