// Code generated by go-go-goja/cmd/gen-dts. DO NOT EDIT.

declare module "durableobjects" {
  export interface FetchRequest { method: string; url?: string; path: string; query?: Record<string, unknown>; headers?: Record<string, string>; body?: unknown; rawBody?: string }
  export interface FetchResponse { status: number; headers?: Record<string, string>; body?: unknown }
  export interface MountableHTTPHandler { readonly type?: string }
  /** Dispatches RPC to an object and blocks until any returned object-handler Promise settles. */
  export function rpc(namespace: string, name: string, method: string, args?: unknown[]): unknown;
  /** Dispatches fetch to an object and blocks until any returned object-handler Promise settles. */
  export function fetch(namespace: string, name: string, request: FetchRequest): FetchResponse;
  /** Dispatches RPC to the current authenticated actor's private object. Only available in a planned route with a host-provided bound dispatcher. */
  export function rpcForActor(namespace: string, method: string, args?: unknown[]): unknown;
  /** Dispatches fetch to the current authenticated actor's private object. Only available in a planned route with a host-provided bound dispatcher. */
  export function fetchForActor(namespace: string, request: FetchRequest): FetchResponse;
  /** Returns the raw caller-named gateway only when enableRawGateway is explicitly true. */
  export function gateway(): MountableHTTPHandler;
  /** Alias for gateway(). */
  export function handler(): MountableHTTPHandler;
}

declare module "express" {
  export function app(): App;
  export function user(): UserAuthBuilder;
  export function resource(type: string): ResourceBuilder;
  export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "ALL" | string;
  export interface App {
  route(method: HttpMethod, pattern: string): RouteNeedsSecurity;
  get(pattern: string): RouteNeedsSecurity;
  post(pattern: string): RouteNeedsSecurity;
  put(pattern: string): RouteNeedsSecurity;
  patch(pattern: string): RouteNeedsSecurity;
  delete(pattern: string): RouteNeedsSecurity;
  all(pattern: string): RouteNeedsSecurity;
  mount(prefix: string, handler: MountableHandler, options?: MountOptions): void;
  mountHandler(prefix: string, handler: MountableHandler, options?: MountOptions): void;
  static(prefix: string, directory: string): void;
  staticFromAssetsModule(prefix: string, assetsModule: unknown, root: string): void;
  spaFromAssetsModule(prefix: string, assetsModule: unknown, root: string, options?: { index?: string; excludePrefixes?: string[] }): void;
  }
  export interface MountableHandler {}
  export interface MountOptions { stripPrefix?: boolean; excludePrefixes?: string[]; }
  export interface RouteNeedsSecurity {
  name(name: string): RouteNeedsSecurity;
  public(): RouteNeedsHandler;
  auth(spec: UserAuthSpec): RouteNeedsPolicy;
  }
  export interface RouteNeedsPolicy {
  resource(spec: ResourceSpec): RouteNeedsPolicy;
  csrf(required?: boolean): RouteNeedsPolicy;
  audit(event: string): RouteNeedsPolicy;
  allow(action: string): RouteNeedsHandler;
  }
  export interface RouteNeedsHandler {
  csrf(required?: boolean): RouteNeedsHandler;
  audit(event: string): RouteNeedsHandler;
  handle(handler: PlannedHandler): void;
  }
  export interface UserAuthBuilder {
  required(): UserAuthSpec;
  mfaFresh(duration: string): UserAuthSpec;
  }
  export type UserAuthSpec = UserAuthBuilder;
  export interface ResourceBuilder {
  named(name: string): ResourceSpec;
  idFromParam(param: string): ResourceSpec;
  fromParam(param: string): ResourceSpec;
  tenantFromParam(param: string): ResourceSpec;
  withinTenantParam(param: string): ResourceSpec;
  mustExist(): ResourceSpec;
  }
  export type ResourceSpec = ResourceBuilder;
  export type PlannedHandler = (ctx: PlannedContext, res: Response) => unknown;
  export type Handler = PlannedHandler;
  export interface PlannedContext {
  request: Request;
  actor: Actor | null;
  body: unknown;
  params: Record<string, string>;
  resources: Record<string, ResourceRef>;
  resource(name: string): ResourceRef | null;
  action: string;
  routeName: string;
  }
  export interface Actor { id: string; kind: string; tenantIds?: string[]; claims?: Record<string, unknown>; }
  export interface ResourceRef { name: string; type: string; id: string; tenantId?: string; claims?: Record<string, unknown>; }
  export interface Request {
  method: string;
  url: string;
  path: string;
  query: Record<string, string | string[]>;
  params: Record<string, string>;
  headers: Record<string, string>;
  cookies: Record<string, string>;
  session: Session | null;
  ip: string;
  body: unknown;
  rawBody: string;
  }
  export interface Session { id: string; isNew: boolean; cookieName: string; }
  export interface Response {
  status(code: number): Response;
  set(name: string, value: string): Response;
  type(value: string): Response;
  json(value: unknown): void;
  send(value?: unknown): void;
  html(value: unknown): void;
  redirect(url: string): void;
  redirect(status: number, url: string): void;
  end(): void;
  }
}

declare module "fs:assets" {
  export function appendFile(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): Promise<void>;
  export function appendFileSync(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): void;
  export function capabilities(): FSCapabilities;
  export function copyFile(src: string, dst: string): Promise<void>;
  export function copyFileSync(src: string, dst: string): void;
  export function exists(path: string): Promise<boolean>;
  export function existsSync(path: string): boolean;
  export function mkdir(path: string, options?: {  }): Promise<void>;
  export function mkdirSync(path: string, options?: {  }): void;
  export function readFile(path: string, encoding?: string | {  }): Promise<string | Buffer>;
  export function readFileSync(path: string, encoding?: string | {  }): string | Buffer;
  export function readdir(path: string): Promise<string[]>;
  export function readdirSync(path: string): string[];
  export function rename(oldPath: string, newPath: string): Promise<void>;
  export function renameSync(oldPath: string, newPath: string): void;
  export function rm(path: string, options?: {  }): Promise<void>;
  export function rmSync(path: string, options?: {  }): void;
  export function stat(path: string): Promise<FileStats>;
  export function statSync(path: string): FileStats;
  export function unlink(path: string): Promise<void>;
  export function unlinkSync(path: string): void;
  export function writeFile(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): Promise<void>;
  export function writeFileSync(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): void;
  interface FileStats {
  name: string;
  size: number;
  mode: number;
  modTime: string;
  isDir: boolean;
  isFile: boolean;
  }
  interface FSMountInfo {
  mount: string;
  root: string;
  }
  interface FSCapabilities {
  backend: string;
  read: boolean;
  write: boolean;
  embedded: boolean;
  mounts?: FSMountInfo[];
  }
  export const isReadOnly: boolean;
}

declare module "timer" {
  export function sleep(ms: number): Promise<void>;
}
