// Code generated by logcopter-gen; DO NOT EDIT.

package idpcontinuationtest

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.pkg.idpcontinuation.idpcontinuationtest")
