// Code generated by logcopter-gen; DO NOT EDIT.

package tinyidp

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.internal.gojamodules.tinyidp")
