// Code generated by logcopter-gen; DO NOT EDIT.

package resourceauth

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.cmd.tinyidp-xapp.internal.resourceauth")
