import { FormEvent, useState } from "react";
import { useCreateAccountMutation, useCreateMessageMutation, useFeedQuery, useLogoutMutation, useRegistrationQuery, useSessionQuery } from "./api";

export default function App(){
 const session=useSessionQuery(); const feed=useFeedQuery(); const [logout]=useLogoutMutation();
 if(session.isLoading)return <Notice text="Checking desk session…"/>;
 if(session.error)return <Notice text="The desk is temporarily unavailable."/>;
 const me=session.data!;
 return <main className="desk"><header className="mast"><p className="kicker">TINY-IDP / LOCAL SERVICE</p><div className="mast-row"><div><h1>Message Desk</h1><p className="deck">A small, persistent place for notes left in plain sight.</p></div><div className="status"><span>{me.authenticated?"SIGNED IN":"GUEST MODE"}</span>{me.authenticated?<><b>{me.displayName}</b><button className="quiet" onClick={()=>logout({csrf:me.csrfToken!})}>Log out</button></>:<a className="quiet" href="/auth/login?return_to=/">Sign in</a>}</div></div></header>
 <div className="layout"><aside><Intro/><>{me.authenticated?<Composer csrf={me.csrfToken!}/>:<Welcome/>}</></aside><section className="feed"><div className="feed-heading"><div><p className="kicker accent">CURRENT NOTES</p><h2>From the desk</h2></div><span>{feed.data?.messages.length??0} SHOWN</span></div>{feed.isLoading?<Notice text="Loading notes…"/>:null}{feed.error?<Notice text="Notes could not be loaded."/>:null}{feed.data?.messages.length===0?<div className="empty">□<h3>No notes yet.</h3><p>The first message will stay here after a restart.</p></div>:null}{feed.data?.messages.map(m=><article className="note" key={m.id}><div className="note-meta"><b>{m.authorName}</b><time>{new Date(m.createdAt).toLocaleString()}</time></div><p>{m.body}</p></article>)}</section></div><footer>MESSAGE DESK <span>IDENTITY BY TINY-IDP</span></footer></main>
}
function Intro(){return <section className="intro"><p className="kicker accent">01 / ABOUT</p><h2>Leave a clear record.</h2><p>Messages are stored locally. Sign in to add one; everyone may read the desk.</p></section>}
function Welcome(){const reg=useRegistrationQuery(); const [create,created]=useCreateAccountMutation(); const [login,setLogin]=useState("");const [name,setName]=useState("");const [password,setPassword]=useState("");const [confirmation,setConfirmation]=useState(""); const submit=async(e:FormEvent)=>{e.preventDefault();if(!reg.data)return;await create({csrf:reg.data.csrfToken,body:{login,displayName:name,password,passwordConfirmation:confirmation}}).unwrap();location.assign("/auth/login?return_to=/")};return <section className="composer"><p className="kicker">02 / JOIN</p><h2>Open an account</h2><form onSubmit={submit}><label>NAME<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>LOGIN<input value={login} onChange={e=>setLogin(e.target.value)} required/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>CONFIRM PASSWORD<input type="password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></label><button disabled={!reg.data||created.isLoading}>{created.isLoading?"Creating…":"Create account"}</button>{created.error?<p className="error">Account could not be created.</p>:null}</form><a className="quiet" href="/auth/login?return_to=/">I already have an account</a></section>}
function Composer({csrf}:{csrf:string}){const [body,setBody]=useState("");const [create,state]=useCreateMessageMutation();const submit=async(e:FormEvent)=>{e.preventDefault();await create({body,csrf}).unwrap();setBody("")};return <section className="composer"><p className="kicker">02 / WRITE</p><h2>Leave a note</h2><form onSubmit={submit}><label>MESSAGE<textarea rows={6} value={body} onChange={e=>setBody(e.target.value)} maxLength={1000} required/></label><div className="form-foot"><span>{body.length} / 1000</span><button disabled={state.isLoading}>{state.isLoading?"Placing…":"Place note"}</button></div>{state.error?<p className="error">Message could not be placed.</p>:null}</form></section>}
function Notice({text}:{text:string}){return <div className="notice">{text}</div>}
