// Code generated by logcopter-gen; DO NOT EDIT.

package productionui

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("tinyidp.internal.productionui")
